// Demo User Profile
export const demoUser = {
    id: 'demo-user-001',
    name: 'Amy',
    email: 'amy@demo.com',
    avatar: '/images/demo/avatar.jpg',
    skinProfile: {
        skinType: 'combination' as const,
        skinToneMonk: 5,
        skinToneHex: '#d7bd96',
        undertone: 'warm' as const,
        concerns: ['pores', 'mild_acne', 'uneven_tone'],
        allergies: [],
    },
    preferences: {
        style: 'natural',
        brands: ['MAC', 'Lancome', 'YSL'],
        budgetRange: [100, 500],
    },
    streak: 15,
    joinDate: '2024-10-01',
};

// Mock Skin Analysis Results
export const mockAnalysis = {
    id: 'analysis-001',
    date: '2024-12-15',
    overallScore: 78,
    metrics: {
        hydration: { score: 65, status: 'moderate', trend: '+5', icon: '💧' },
        oil: { score: 42, status: 'good', trend: '-3', icon: '✨' },
        pores: { score: 55, status: 'visible', trend: '+2', icon: '🔍' },
        wrinkles: { score: 85, status: 'minimal', trend: '0', icon: '🌟' },
        darkCircles: { score: 60, status: 'mild', trend: '+8', icon: '👁️' },
        acne: { score: 72, status: 'few', trend: '+10', icon: '🫧' },
        sensitivity: { score: 80, status: 'low', trend: '0', icon: '🛡️' },
        brightness: { score: 70, status: 'good', trend: '+3', icon: '☀️' },
    },
    skinTone: {
        monkScale: 5,
        hexColor: '#d7bd96',
        undertone: 'warm',
    },
    problemAreas: [
        { zone: 't-zone', issue: 'oil', severity: 'moderate', x: 50, y: 25 },
        { zone: 'cheeks', issue: 'dryness', severity: 'mild', x: 30, y: 50 },
        { zone: 'nose', issue: 'pores', severity: 'visible', x: 50, y: 45 },
        { zone: 'forehead', issue: 'spots', severity: 'mild', x: 50, y: 15 },
    ],
    recommendations: [
        '建议使用平衡型爽肤水调理T区油脂分泌',
        '晚间护肤可加入补水精华，改善面颊干燥',
        '您的皮肤状态较上月提升了5%，继续保持！',
    ],
};

// Mock Analysis History for Trends
export const mockAnalysisHistory = [
    { date: '2024-11-15', score: 72, hydration: 58, oil: 48 },
    { date: '2024-11-22', score: 74, hydration: 60, oil: 46 },
    { date: '2024-11-29', score: 75, hydration: 62, oil: 45 },
    { date: '2024-12-06', score: 76, hydration: 63, oil: 44 },
    { date: '2024-12-13', score: 78, hydration: 65, oil: 42 },
];

// Mock Makeup Styles
export const mockStyles = [
    {
        id: 'style-001',
        name: '清透职场妆',
        nameEn: 'Natural Office Glow',
        description: '简约清新，适合日常办公场合',
        difficulty: 2,
        duration: 8,
        occasion: 'work',
        thumbnail: '/images/styles/natural-office.jpg',
        matchScore: 95,
        matchReason: '与您的肤色和职业风格完美匹配',
        trendSource: null,
        products: ['product-001', 'product-002', 'product-003'],
        steps: 5,
    },
    {
        id: 'style-002',
        name: '温柔约会妆',
        nameEn: 'Soft Glam Date Night',
        description: '温柔甜美，适合约会和聚会',
        difficulty: 3,
        duration: 15,
        occasion: 'date',
        thumbnail: '/images/styles/soft-glam.jpg',
        matchScore: 88,
        matchReason: '暖色调与您的肤色相得益彰',
        trendSource: 'xiaohongshu',
        trendEngagement: 15200,
        products: ['product-002', 'product-004', 'product-005'],
        steps: 7,
    },
    {
        id: 'style-003',
        name: '清冷感妆容',
        nameEn: 'Clean Girl Aesthetic',
        description: '当下最流行的清冷高级感',
        difficulty: 2,
        duration: 10,
        occasion: 'casual',
        thumbnail: '/images/styles/clean-girl.jpg',
        matchScore: 82,
        matchReason: '简约风格突出您的自然美',
        trendSource: 'tiktok',
        trendEngagement: 89000,
        products: ['product-001', 'product-006'],
        steps: 4,
    },
    {
        id: 'style-004',
        name: '复古港风妆',
        nameEn: 'Retro HK Style',
        description: '经典港风，气场全开',
        difficulty: 4,
        duration: 20,
        occasion: 'party',
        thumbnail: '/images/styles/retro-hk.jpg',
        matchScore: 75,
        matchReason: '红唇与您的五官相配',
        trendSource: 'xiaohongshu',
        trendEngagement: 25600,
        products: ['product-003', 'product-007', 'product-008'],
        steps: 8,
    },
];

// Mock Products
export const mockProducts = [
    {
        id: 'product-001',
        name: '小黑瓶精华液',
        nameEn: 'Advanced Genifique Serum',
        brand: 'Lancome',
        category: 'skincare',
        subcategory: 'serum',
        price: 950,
        originalPrice: 1100,
        currency: 'CNY',
        volume: '50ml',
        rating: 4.8,
        reviewCount: 12500,
        image: '/images/products/lancome-serum.jpg',
        suitableSkinTypes: ['all'],
        skinConcerns: ['anti-aging', 'hydration', 'brightness'],
        description: '经典抗老精华，富含益生菌精粹',
    },
    {
        id: 'product-002',
        name: '子弹头口红 Chili色',
        nameEn: 'Matte Revolution Lipstick - Chili',
        brand: 'MAC',
        category: 'makeup',
        subcategory: 'lipstick',
        price: 170,
        originalPrice: 170,
        currency: 'CNY',
        volume: '3g',
        rating: 4.7,
        reviewCount: 8900,
        image: '/images/products/mac-chili.jpg',
        suitableSkinTypes: ['all'],
        skinConcerns: [],
        description: '经典砖红色，显白百搭',
    },
    {
        id: 'product-003',
        name: '五花肉高光盘',
        nameEn: 'Highlighting Powder Palette',
        brand: 'NARS',
        category: 'makeup',
        subcategory: 'highlighter',
        price: 420,
        originalPrice: 420,
        currency: 'CNY',
        volume: '14g',
        rating: 4.6,
        reviewCount: 5600,
        image: '/images/products/nars-highlighter.jpg',
        suitableSkinTypes: ['all'],
        skinConcerns: [],
        description: '四色高光，打造立体妆容',
    },
    {
        id: 'product-004',
        name: '持妆粉底液',
        nameEn: 'Teint Idole Ultra Wear Foundation',
        brand: 'Lancome',
        category: 'makeup',
        subcategory: 'foundation',
        price: 480,
        originalPrice: 480,
        currency: 'CNY',
        volume: '30ml',
        rating: 4.5,
        reviewCount: 7800,
        image: '/images/products/lancome-foundation.jpg',
        suitableSkinTypes: ['combination', 'oily'],
        skinConcerns: ['coverage', 'longevity'],
        description: '24小时持妆，自然遮瑕',
    },
    {
        id: 'product-005',
        name: '九色眼影盘',
        nameEn: 'Eye Palette - Soft Glam',
        brand: 'Anastasia',
        category: 'makeup',
        subcategory: 'eyeshadow',
        price: 520,
        originalPrice: 580,
        currency: 'CNY',
        volume: '1pc',
        rating: 4.8,
        reviewCount: 9200,
        image: '/images/products/abh-palette.jpg',
        suitableSkinTypes: ['all'],
        skinConcerns: [],
        description: '大地色系，日常百搭',
    },
    {
        id: 'product-006',
        name: '丝绒哑光唇釉',
        nameEn: 'Velvet Matte Lip Stain',
        brand: 'YSL',
        category: 'makeup',
        subcategory: 'lipstick',
        price: 320,
        originalPrice: 320,
        currency: 'CNY',
        volume: '6ml',
        rating: 4.7,
        reviewCount: 6300,
        image: '/images/products/ysl-lip.jpg',
        suitableSkinTypes: ['all'],
        skinConcerns: [],
        description: '丝绒质地，显色持久',
    },
];

// Mock User Inventory
export const mockInventory = [
    {
        id: 'inv-001',
        productId: 'product-001',
        product: mockProducts[0],
        purchaseDate: '2024-11-01',
        openDate: '2024-11-05',
        totalAmount: 50,
        remainingPercent: 40,
        estimatedDaysLeft: 15,
        status: 'running_low',
    },
    {
        id: 'inv-002',
        productId: 'product-002',
        product: mockProducts[1],
        purchaseDate: '2024-10-15',
        openDate: '2024-10-15',
        totalAmount: 3,
        remainingPercent: 15,
        estimatedDaysLeft: 7,
        status: 'critical',
    },
    {
        id: 'inv-003',
        productId: 'product-004',
        product: mockProducts[3],
        purchaseDate: '2024-11-20',
        openDate: '2024-11-20',
        totalAmount: 30,
        remainingPercent: 70,
        estimatedDaysLeft: 45,
        status: 'good',
    },
    {
        id: 'inv-004',
        productId: 'product-005',
        product: mockProducts[4],
        purchaseDate: '2024-09-01',
        openDate: '2024-09-01',
        totalAmount: 1,
        remainingPercent: 55,
        estimatedDaysLeft: 60,
        status: 'good',
    },
];

// Mock Trends
export const mockTrends = [
    {
        id: 'trend-001',
        name: '水光肌',
        nameEn: 'Glass Skin',
        source: 'xiaohongshu',
        sourceIcon: '📕',
        engagement: 125000,
        trendScore: 95,
        description: '打造通透水润的玻璃肌效果',
        hashtag: '#水光肌',
    },
    {
        id: 'trend-002',
        name: '拿铁妆',
        nameEn: 'Latte Makeup',
        source: 'tiktok',
        sourceIcon: '🎵',
        engagement: 89000,
        trendScore: 88,
        description: '温暖咖啡色系，知性优雅',
        hashtag: '#LatteGirl',
    },
    {
        id: 'trend-003',
        name: '氛围感眼妆',
        nameEn: 'Soft Focus Eyes',
        source: 'xiaohongshu',
        sourceIcon: '📕',
        engagement: 76000,
        trendScore: 82,
        description: '柔焦晕染，打造迷离眼神',
        hashtag: '#氛围感',
    },
    {
        id: 'trend-004',
        name: '果汁唇',
        nameEn: 'Juicy Lips',
        source: 'instagram',
        sourceIcon: '📷',
        engagement: 65000,
        trendScore: 78,
        description: '水润果冻感，元气满满',
        hashtag: '#JuicyLips',
    },
];

// Mock Tutorials
export const mockTutorials = [
    {
        id: 'tutorial-001',
        styleId: 'style-001',
        title: '清透职场妆教程',
        titleEn: 'Natural Office Glow Tutorial',
        description: '5分钟搞定日常通勤妆容',
        difficulty: 2,
        duration: 8,
        thumbnail: '/images/tutorials/natural-office.jpg',
        steps: [
            {
                stepNumber: 1,
                title: '底妆打底',
                description: '使用妆前乳均匀涂抹全脸，重点在T区',
                arOverlayType: 'full_face',
                products: ['product-004'],
                tips: ['少量多次，避免厚重'],
                duration: 60,
            },
            {
                stepNumber: 2,
                title: '粉底上妆',
                description: '用美妆蛋将粉底液轻拍上脸',
                arOverlayType: 'full_face',
                products: ['product-004'],
                tips: ['从中心向外晕染', '鼻翼处仔细遮盖'],
                duration: 90,
            },
            {
                stepNumber: 3,
                title: '眉毛修饰',
                description: '顺着眉毛生长方向轻轻描画',
                arOverlayType: 'eyebrow',
                products: [],
                tips: ['眉头轻、眉尾重'],
                duration: 60,
            },
            {
                stepNumber: 4,
                title: '眼影晕染',
                description: '大地色打底，加深眼尾',
                arOverlayType: 'eyeshadow',
                products: ['product-005'],
                tips: ['少量多次叠加'],
                duration: 90,
            },
            {
                stepNumber: 5,
                title: '唇部上色',
                description: '涂抹唇膏，打造自然唇色',
                arOverlayType: 'lips',
                products: ['product-002'],
                tips: ['先用唇刷勾勒唇形'],
                duration: 45,
            },
        ],
        relatedProducts: mockProducts.slice(0, 3),
    },
    {
        id: 'tutorial-002',
        styleId: 'style-002',
        title: '温柔约会妆教程',
        titleEn: 'Soft Glam Date Tutorial',
        description: '打造甜美温柔的约会妆容',
        difficulty: 3,
        duration: 15,
        thumbnail: '/images/tutorials/soft-glam.jpg',
        steps: [
            {
                stepNumber: 1,
                title: '妆前护肤',
                description: '做好保湿打底',
                arOverlayType: 'full_face',
                products: ['product-001'],
                tips: ['等待精华完全吸收'],
                duration: 60,
            },
            // More steps would be added
        ],
        relatedProducts: mockProducts.slice(1, 5),
    },
];

// Mock Price History
export const mockPriceHistory = {
    'product-001': [
        { date: '2024-09-01', price: 1100 },
        { date: '2024-10-01', price: 1050 },
        { date: '2024-11-01', price: 980 },
        { date: '2024-11-11', price: 760 }, // 双11
        { date: '2024-11-15', price: 950 },
        { date: '2024-12-01', price: 950 },
        { date: '2024-12-12', price: 850 }, // 双12
        { date: '2024-12-15', price: 950 },
    ],
    'product-002': [
        { date: '2024-09-01', price: 170 },
        { date: '2024-10-01', price: 170 },
        { date: '2024-11-11', price: 136 }, // 双11
        { date: '2024-12-01', price: 170 },
    ],
};

// Mock Smart Shopping Alerts
export const mockShoppingAlerts = [
    {
        id: 'alert-001',
        type: 'replenish',
        productId: 'product-002',
        product: mockProducts[1],
        message: '您的 MAC Chili 口红即将用完',
        detail: '预计还能使用 7 天，618 大促即将到来',
        urgency: 'high',
        suggestedAction: '立即补货',
        expectedSale: '2025-06-18',
        expectedPrice: 136,
    },
    {
        id: 'alert-002',
        type: 'price_drop',
        productId: 'product-001',
        product: mockProducts[0],
        message: '兰蔻小黑瓶降价提醒',
        detail: '当前价格 ¥950，低于您设定的 ¥1000 提醒价',
        urgency: 'medium',
        suggestedAction: '查看详情',
    },
    {
        id: 'alert-003',
        type: 'trending',
        productId: 'product-006',
        product: mockProducts[5],
        message: 'YSL 唇釉正在流行',
        detail: '与您关注的"拿铁妆"趋势相关',
        urgency: 'low',
        suggestedAction: '了解更多',
    },
];

// User Activity Feed
export const mockActivityFeed = [
    {
        id: 'activity-001',
        type: 'tutorial_completed',
        title: '完成教程：清透职场妆',
        timestamp: '2024-12-15 09:30',
        icon: '🎓',
    },
    {
        id: 'activity-002',
        type: 'inventory_added',
        title: '添加产品：YSL 唇釉',
        timestamp: '2024-12-14 18:20',
        icon: '📦',
    },
    {
        id: 'activity-003',
        type: 'analysis_completed',
        title: '皮肤分析：评分提升至 78',
        timestamp: '2024-12-13 08:15',
        icon: '📊',
    },
    {
        id: 'activity-004',
        type: 'streak',
        title: '连续使用 15 天',
        timestamp: '2024-12-12 08:00',
        icon: '🔥',
    },
];

// Upcoming Calendar Events
export const mockCalendarEvents = [
    {
        id: 'event-001',
        title: '项目汇报',
        date: '2024-12-16',
        time: '14:00',
        type: 'work',
        suggestedStyle: 'style-001',
    },
    {
        id: 'event-002',
        title: '闺蜜聚会',
        date: '2024-12-17',
        time: '19:00',
        type: 'social',
        suggestedStyle: 'style-002',
    },
    {
        id: 'event-003',
        title: '年会',
        date: '2024-12-20',
        time: '18:00',
        type: 'party',
        suggestedStyle: 'style-004',
    },
];

// Monk Skin Tone Scale Colors
export const monkScaleColors = [
    { level: 1, hex: '#f6ede4', name: 'Very Light' },
    { level: 2, hex: '#f3e7db', name: 'Light' },
    { level: 3, hex: '#f7ead0', name: 'Light Medium' },
    { level: 4, hex: '#eadaba', name: 'Medium Light' },
    { level: 5, hex: '#d7bd96', name: 'Medium' },
    { level: 6, hex: '#a07e56', name: 'Medium Tan' },
    { level: 7, hex: '#825c43', name: 'Tan' },
    { level: 8, hex: '#604134', name: 'Dark Tan' },
    { level: 9, hex: '#3a312a', name: 'Dark' },
    { level: 10, hex: '#292420', name: 'Very Dark' },
];

// ========== Workflow Demo Data ==========

// User Context for Workflow
export const mockUserContext = {
    mood: 'calm' as const,
    moodLabel: '平静',
    moodIcon: '😌',
    menstrualPhase: 'normal' as const,
    menstrualLabel: '正常期',
    occasion: 'work' as const,
    occasionLabel: '上班',
    schedule: ['09:00 部门会议', '14:00 客户演示', '16:00 项目评审'],
    weather: { temp: 22, humidity: 65, uv: 3, condition: '多云' },
};

// Mood Options
export const moodOptions = [
    { id: 'happy', label: '开心', icon: '😊', skinEffect: '肌肤状态良好' },
    { id: 'calm', label: '平静', icon: '😌', skinEffect: '适合自然妆容' },
    { id: 'tired', label: '疲惫', icon: '😔', skinEffect: '需要遮瑕提亮' },
    { id: 'excited', label: '兴奋', icon: '🤩', skinEffect: '可尝试大胆妆容' },
];

// Menstrual Phase Options
export const menstrualOptions = [
    { id: 'normal', label: '正常期', skinEffect: '皮肤状态稳定' },
    { id: 'period', label: '经期', skinEffect: '皮肤较敏感，建议温和妆容' },
    { id: 'pms', label: '经前期', skinEffect: '可能出油较多，注意控油' },
];

// Occasion Options
export const occasionOptions = [
    { id: 'work', label: '上班', icon: '💼', style: '简约专业' },
    { id: 'date', label: '约会', icon: '💕', style: '温柔甜美' },
    { id: 'party', label: '派对', icon: '🎉', style: '亮眼夺目' },
    { id: 'casual', label: '休闲', icon: '☕', style: '自然舒适' },
];

// AI Search Steps Animation
export const mockAISearchSteps = [
    { id: 1, text: '分析您的肤色和肤质...', icon: '🔍', delay: 0 },
    { id: 2, text: '搜索小红书热门妆容趋势...', icon: '📕', delay: 800 },
    { id: 3, text: '搜索抖音流行妆容...', icon: '🎵', delay: 1400 },
    { id: 4, text: '匹配适合混合肌的产品...', icon: '✨', delay: 2000 },
    { id: 5, text: '考虑职场场合需求...', icon: '💼', delay: 2600 },
    { id: 6, text: '综合生理期皮肤状态...', icon: '📅', delay: 3200 },
    { id: 7, text: '生成个性化推荐...', icon: '🎯', delay: 3800 },
];

// Makeup Steps for Workflow
export const mockMakeupSteps = [
    {
        id: 1,
        title: '妆前打底',
        titleEn: 'Primer',
        area: 'full_face' as const,
        duration: 60,
        description: '使用妆前乳均匀涂抹全脸，轻拍至吸收',
        detailedSteps: ['取黄豆大小妆前乳', '从脸中央向外推开', '重点照顾T区毛孔'],
        tips: ['由内向外推开', '少量多次', 'T区可多涂一层'],
        product: { name: '兰蔻妆前乳', brand: 'Lancome', id: 'product-001' },
        commonIssues: ['涂抹不均匀', '用量过多'],
    },
    {
        id: 2,
        title: '底妆上妆',
        titleEn: 'Foundation',
        area: 'full_face' as const,
        duration: 90,
        description: '用美妆蛋将粉底液轻拍上脸，打造轻薄底妆',
        detailedSteps: ['湿润美妆蛋', '点涂粉底液在额头、脸颊、下巴', '轻拍晕开'],
        tips: ['美妆蛋要充分湿润', '从中心向外晕染', '鼻翼处仔细遮盖'],
        product: { name: '持妆粉底液', brand: 'Lancome', id: 'product-004' },
        commonIssues: ['厚重假面', '颜色不匹配', '卡粉'],
    },
    {
        id: 3,
        title: '眉毛塑形',
        titleEn: 'Eyebrow',
        area: 'eyebrow' as const,
        duration: 60,
        description: '顺着眉毛生长方向轻轻描画，打造自然眉形',
        detailedSteps: ['先用眉刷梳理眉毛', '从眉中开始描画', '眉头用眉刷轻扫自然'],
        tips: ['眉头轻、眉尾重', '颜色比发色浅一度', '眉峰不要太锐利'],
        product: { name: '自然眉笔', brand: 'Benefit', id: 'product-007' },
        commonIssues: ['眉头太重', '眉形不对称', '颜色太深'],
    },
    {
        id: 4,
        title: '眼影晕染',
        titleEn: 'Eyeshadow',
        area: 'eyeshadow' as const,
        duration: 90,
        description: '大地色打底，加深眼尾，打造深邃眼妆',
        detailedSteps: ['浅色铺满眼窝', '中间色晕染眼褶', '深色加深眼尾和下眼线'],
        tips: ['少量多次叠加', '注意晕染边界', '下眼影不要太重'],
        product: { name: '九色眼影盘', brand: 'Anastasia', id: 'product-005' },
        commonIssues: ['晕染不均匀', '颜色太脏', '范围过大'],
    },
    {
        id: 5,
        title: '唇妆涂抹',
        titleEn: 'Lipstick',
        area: 'lips' as const,
        duration: 45,
        description: '涂抹唇膏，打造自然饱满唇色',
        detailedSteps: ['先用润唇膏打底', '从唇中央开始涂抹', '用手指轻拍边缘自然'],
        tips: ['先用唇刷勾勒唇形', '可叠加打造渐变', '唇峰要描清晰'],
        product: { name: '子弹头口红 Chili', brand: 'MAC', id: 'product-002' },
        commonIssues: ['涂出唇线', '颜色不均匀', '太干燥'],
    },
];

// Operation Feedback Examples
export const mockOperationFeedback = [
    {
        id: 'feedback-001',
        step: 2,
        issue: '粉底涂抹稍厚',
        suggestion: '建议用湿润的美妆蛋轻拍，让底妆更轻薄透气',
        severity: 'warning' as const,
        area: 'foundation',
        timestamp: '00:45',
    },
    {
        id: 'feedback-002',
        step: 4,
        issue: '眼影晕染范围过小',
        suggestion: '建议向眼尾方向延伸，打造更深邃的眼型',
        severity: 'warning' as const,
        area: 'eyeshadow',
        timestamp: '02:30',
    },
    {
        id: 'feedback-003',
        step: 4,
        issue: '左右眼影不对称',
        suggestion: '右眼眼尾可以再加深一点，与左眼保持一致',
        severity: 'info' as const,
        area: 'eyeshadow',
        timestamp: '03:15',
    },
    {
        id: 'feedback-004',
        step: 5,
        issue: '唇形描绘完美',
        suggestion: '很棒！唇形饱满自然，颜色也很适合您的肤色',
        severity: 'success' as const,
        area: 'lips',
        timestamp: '04:20',
    },
];

// Product Alerts for Workflow
export const mockProductAlerts = [
    {
        id: 'product-alert-001',
        productId: 'product-002',
        productName: 'MAC Chili 口红',
        brand: 'MAC',
        alertType: 'low_quantity' as const,
        remaining: 20,
        message: '剩余约 20%，建议尽快补货',
        urgency: 'high' as const,
        suggestedAction: '立即购买',
        price: 170,
        salePrice: 136,
        nextSale: '618大促',
    },
    {
        id: 'product-alert-002',
        productId: null,
        productName: '冷色调眼影',
        brand: null,
        alertType: 'not_suitable' as const,
        remaining: null,
        message: '当前眼影盘偏冷色调，不太适合今日选择的暖色妆容',
        urgency: 'medium' as const,
        suggestedProduct: 'Urban Decay Naked Heat',
        suggestedBrand: 'Urban Decay',
        price: 420,
    },
    {
        id: 'product-alert-003',
        productId: 'product-001',
        productName: '兰蔻妆前乳',
        brand: 'Lancome',
        alertType: 'expiring_soon' as const,
        remaining: 40,
        message: '开封已超过6个月，建议尽快用完或更换',
        urgency: 'medium' as const,
        suggestedAction: '查看新品',
    },
];

// ========== CES 2026 Competitive Analysis ==========

// Competitor Products from CES 2026
export const ces2026Competitors = [
    {
        id: 'competitor-001',
        name: 'Samsung AI Beauty Mirror',
        nameZh: '三星 AI 美妆镜',
        company: 'Samsung × Amorepacific',
        companyLogo: '🔷',
        category: 'smart_mirror',
        launchDate: 'CES 2026',
        features: [
            { name: '光学皮肤诊断', description: '通过内置摄像头评估毛孔、泛红、色素沉着和皱纹' },
            { name: '45万数据集', description: '基于45万+皮肤案例训练的AI模型' },
            { name: 'LED面膜联动', description: '与makeON ONFACE LED面膜配合使用' },
        ],
        strengths: ['大品牌背书', '硬件集成能力强', '数据量大'],
        weaknesses: ['无实时化妆指导', '缺乏个性化妆容推荐', '无产品库存监控'],
        price: '预估 ¥8,000+',
        techHighlight: '4K光学传感器 + 红外传感器',
        source: 'https://www.cosmeticsdesign-europe.com/Article/2026/01/06/ai-led-and-smart-styling-key-beauty-tech-trends-at-ces-2026/',
    },
    {
        id: 'competitor-002',
        name: 'Skinsight™ Platform',
        nameZh: 'Skinsight™ 电子皮肤平台',
        company: 'Amorepacific × MIT',
        companyLogo: '🧬',
        category: 'wearable_sensor',
        launchDate: 'CES 2026',
        award: 'CES Innovation Award Honoree',
        features: [
            { name: '电子皮肤贴片', description: '皮肤贴合式传感器，测量多种老化因子' },
            { name: '实时老化信号', description: '分析暴露因素和生活方式对皮肤的影响' },
            { name: 'AI个性化护肤', description: '根据分析结果提供定制护肤建议' },
        ],
        strengths: ['MIT联合研发', '精准传感技术', '预测性分析'],
        weaknesses: ['仅限护肤分析', '无化妆指导功能', '需要贴片耗材'],
        price: '预估 ¥3,000+',
        techHighlight: '下一代电子皮肤传感技术',
        source: 'https://www.prnewswire.com/news-releases/amorepacific-showcases-innovative-technologies-at-ces-2026-302652329.html',
    },
    {
        id: 'competitor-003',
        name: 'YouCam AI Agent',
        nameZh: 'YouCam AI 美妆助手',
        company: 'Perfect Corp',
        companyLogo: '📸',
        category: 'ai_software',
        launchDate: 'CES 2026',
        features: [
            { name: '对话式AI助手', description: '通过自然语言对话提供个性化美妆体验' },
            { name: '单张自拍分析', description: '上传自拍即可获得皮肤问题分析' },
            { name: 'AR虚拟试妆', description: '实时虚拟试妆和发型预览' },
        ],
        strengths: ['对话交互自然', 'AR技术成熟', '全球品牌合作多'],
        weaknesses: ['依赖手机/平板', '无专用硬件', '无实时操作反馈'],
        price: 'B端授权 / 消费端免费',
        techHighlight: 'AI Agent + AR虚拟试妆',
        source: 'https://www.businesswire.com/news/home/20251219606970/en/Perfect-Corp.-Unveils-Next-Generation-AI-Beauty-Agent-and-API-Innovations-Transforming-Beauty-Skincare-and-Retail-at-CES-2026',
    },
    {
        id: 'competitor-004',
        name: 'Ceragem Balance AI',
        nameZh: 'Ceragem AI 智能淋浴系统',
        company: 'Ceragem',
        companyLogo: '🚿',
        category: 'smart_mirror',
        launchDate: 'CES 2026',
        features: [
            { name: '无摄像头设计', description: '使用近红外和光谱传感器，保护隐私' },
            { name: '皮肤状态评估', description: '评估水分、油脂、弹性和色素沉着' },
            { name: '智能水质调节', description: '通过电解实时调整水的pH值' },
        ],
        strengths: ['隐私友好', '水疗+护肤一体', '创新传感方案'],
        weaknesses: ['安装成本高', '无化妆功能', '场景受限'],
        price: '预估 ¥15,000+',
        techHighlight: '近红外 + 光谱传感器',
        source: 'https://www.personalcareinsights.com/news/beauty-tech-ces-2026.html',
    },
    {
        id: 'competitor-005',
        name: 'L\'Oréal LED Face Mask',
        nameZh: '欧莱雅 LED 面膜',
        company: 'L\'Oréal × I-Smart',
        companyLogo: '💄',
        category: 'beauty_device',
        launchDate: '2027 (原型展示)',
        award: 'CES 2026 Innovation Award',
        features: [
            { name: '红光+近红外', description: '双波长光疗，改善细纹和肤色不均' },
            { name: '超薄硅胶设计', description: '轻便无创，可融入日常护肤' },
            { name: '10分钟自动疗程', description: '智能计时，使用便捷' },
        ],
        strengths: ['欧莱雅品牌', '光疗技术成熟', '使用便捷'],
        weaknesses: ['仅限护肤', '无AI分析', '无化妆指导'],
        price: '预估 ¥2,000+',
        techHighlight: 'LED红光 + 近红外光疗',
        source: 'https://beautymatter.com/articles/loreal-lights-up-ces-2026-with-two-new-beauty-tech-devices',
    },
    {
        id: 'competitor-006',
        name: 'NuraLogix Anura Mirror',
        nameZh: 'NuraLogix 魔镜',
        company: 'NuraLogix',
        companyLogo: '🪞',
        category: 'health_mirror',
        launchDate: 'CES 2026',
        features: [
            { name: '100+健康指标', description: '30秒内评估超过100项健康指标' },
            { name: '疾病风险预测', description: '估算多种疾病发生概率' },
            { name: '皮肤+健康整合', description: '将皮肤状态与整体健康关联' },
        ],
        strengths: ['健康+美妆整合', '快速检测', '指标丰富'],
        weaknesses: ['偏健康监测', '无化妆教程', '无产品推荐'],
        price: '预估 ¥5,000+',
        techHighlight: 'Transdermal Optical Imaging',
        source: 'https://www.personalcareinsights.com/news/beauty-tech-ces-2026.html',
    },
    {
        id: 'competitor-007',
        name: 'Kolmar Scar Beauty Device',
        nameZh: 'Kolmar 疤痕美容仪',
        company: 'Kolmar Korea',
        companyLogo: '🏆',
        category: 'beauty_device',
        launchDate: 'CES 2026',
        award: 'CES 2026 Best of Innovation Award',
        features: [
            { name: 'AI疤痕分类', description: '将疤痕分为12种预定义类型' },
            { name: '治疗+遮瑕一体', description: '同时治疗疤痕并提供遮瑕方案' },
            { name: '手机App联动', description: '通过App拍照分析并控制设备' },
        ],
        strengths: ['创新大奖', '垂直场景深耕', 'AI分类精准'],
        weaknesses: ['仅限疤痕场景', '无整体妆容功能', '受众较窄'],
        price: '预估 ¥1,500+',
        techHighlight: 'AI疤痕识别 + 定制配方',
        source: 'https://www.cosmeticsdesign-europe.com/Article/2026/01/06/ai-led-and-smart-styling-key-beauty-tech-trends-at-ces-2026/',
    },
];

// Our Product Advantages
export const agenticMirrorAdvantages = [
    {
        id: 'adv-001',
        title: '全流程 Agentic AI',
        titleEn: 'End-to-End Agentic AI',
        description: '从皮肤分析到妆容推荐，再到实时指导，全流程AI自主决策',
        icon: '🤖',
        competitors: ['三星仅分析', 'Perfect Corp无实时反馈', '其他产品无步骤指导'],
    },
    {
        id: 'adv-002',
        title: '实时化妆反馈',
        titleEn: 'Real-time Makeup Feedback',
        description: 'AI实时监控化妆过程，发现问题即时纠正，像私人化妆师在旁指导',
        icon: '👁️',
        competitors: ['市面上无同类产品提供此功能'],
    },
    {
        id: 'adv-003',
        title: '智能产品管理',
        titleEn: 'Smart Inventory Management',
        description: '监控彩妆用品用量、保质期，智能推荐补货时机和促销信息',
        icon: '📦',
        competitors: ['竞品均无产品库存管理功能'],
    },
    {
        id: 'adv-004',
        title: '多维度个性化',
        titleEn: 'Multi-dimensional Personalization',
        description: '结合皮肤状态、心情、生理期、日程、天气等多维度定制妆容',
        icon: '🎯',
        competitors: ['三星仅考虑皮肤', 'Skinsight仅关注老化', '其他产品维度单一'],
    },
    {
        id: 'adv-005',
        title: '趋势融合推荐',
        titleEn: 'Trend-aware Recommendations',
        description: '实时爬取小红书、抖音流行趋势，将潮流与个人特点结合',
        icon: '📱',
        competitors: ['竞品均无社交媒体趋势整合'],
    },
];

// Competitive Comparison Matrix
export const competitiveMatrix = {
    features: [
        { id: 'skin_analysis', name: '皮肤分析', nameEn: 'Skin Analysis' },
        { id: 'makeup_tutorial', name: '化妆教程', nameEn: 'Makeup Tutorial' },
        { id: 'realtime_feedback', name: '实时反馈', nameEn: 'Real-time Feedback' },
        { id: 'product_management', name: '产品管理', nameEn: 'Product Management' },
        { id: 'trend_integration', name: '趋势整合', nameEn: 'Trend Integration' },
        { id: 'ar_tryon', name: 'AR试妆', nameEn: 'AR Try-on' },
        { id: 'personalization', name: '多维个性化', nameEn: 'Multi-dim Personalization' },
        { id: 'agentic_ai', name: 'Agentic AI', nameEn: 'Agentic AI' },
    ],
    products: [
        {
            id: 'agentic_mirror',
            name: 'AgenticMirror',
            isOurs: true,
            scores: {
                skin_analysis: 5,
                makeup_tutorial: 5,
                realtime_feedback: 5,
                product_management: 5,
                trend_integration: 5,
                ar_tryon: 4,
                personalization: 5,
                agentic_ai: 5,
            },
        },
        {
            id: 'samsung_mirror',
            name: 'Samsung AI Mirror',
            isOurs: false,
            scores: {
                skin_analysis: 5,
                makeup_tutorial: 2,
                realtime_feedback: 1,
                product_management: 1,
                trend_integration: 1,
                ar_tryon: 3,
                personalization: 3,
                agentic_ai: 2,
            },
        },
        {
            id: 'perfect_corp',
            name: 'YouCam AI Agent',
            isOurs: false,
            scores: {
                skin_analysis: 4,
                makeup_tutorial: 3,
                realtime_feedback: 2,
                product_management: 1,
                trend_integration: 2,
                ar_tryon: 5,
                personalization: 3,
                agentic_ai: 3,
            },
        },
        {
            id: 'skinsight',
            name: 'Skinsight™',
            isOurs: false,
            scores: {
                skin_analysis: 5,
                makeup_tutorial: 1,
                realtime_feedback: 1,
                product_management: 1,
                trend_integration: 1,
                ar_tryon: 1,
                personalization: 4,
                agentic_ai: 2,
            },
        },
    ],
};

// CES 2026 Industry Trends
export const ces2026Trends = [
    {
        id: 'trend-ai-agent',
        name: 'AI Agent 智能助手',
        description: '从规则驱动到AI自主决策，美妆AI进入Agent时代',
        icon: '🤖',
        companies: ['Perfect Corp', 'AgenticMirror'],
    },
    {
        id: 'trend-sensor',
        name: '传感器创新',
        description: '近红外、光谱传感器、电子皮肤等非侵入式检测技术',
        icon: '📡',
        companies: ['Amorepacific', 'Ceragem', 'NuraLogix'],
    },
    {
        id: 'trend-led',
        name: 'LED光疗普及',
        description: 'LED面膜、眼膜等光疗设备进入消费级市场',
        icon: '💡',
        companies: ['L\'Oréal', 'LG H&H', 'makeON'],
    },
    {
        id: 'trend-personalization',
        name: '深度个性化',
        description: '从皮肤类型到生活方式，多维度定制美妆方案',
        icon: '🎯',
        companies: ['AgenticMirror', 'Amorepacific'],
    },
];

// Workflow Phases
export const workflowPhases = [
    {
        id: 1,
        title: '面部识别',
        titleEn: 'Face Scan',
        description: '智能镜识别您的面部状况',
        icon: '📷',
    },
    {
        id: 2,
        title: '用户画像',
        titleEn: 'User Context',
        description: '采集心情、场合、日程信息',
        icon: '👤',
    },
    {
        id: 3,
        title: 'AI 匹配',
        titleEn: 'AI Matching',
        description: 'Agentic AI 搜索最佳妆容',
        icon: '🧠',
    },
    {
        id: 4,
        title: '步骤指导',
        titleEn: 'Step Guide',
        description: '详细的化妆步骤引导',
        icon: '📝',
    },
    {
        id: 5,
        title: '实时反馈',
        titleEn: 'Real-time Feedback',
        description: '监控操作并给出建议',
        icon: '👁️',
    },
];
